server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a82327636/-spring-cloud-study-config-repo.git     # 配置git仓库的地址
          search-paths: -spring-cloud-study-config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: a82327636                                             # git仓库的账号
          password: Aa82327636